# Generated by Django 4.2.4 on 2023-09-14 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(choices=[('230 230 250', 'むらさき'), ('240 255 240', 'きみどり'), ('255 255 240', 'きいろ'), ('255 239 213', 'オレンジ'), ('255 240 245', 'ピンク'), ('255 228 225', 'ピンクオレンジ'), ('224 255 255', 'あお'), ('245 245 245', 'グレー'), ('255 182 193', 'あか'), ('102 205 170', 'みどり')], max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'color')},
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タスク名')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='締切')),
                ('importance', models.PositiveIntegerField(choices=[(1, 'とても大事'), (2, '大事'), (3, '普通'), (4, 'あまり大事じゃない'), (5, '全然大事じゃない')], default=3)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TodoDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('importance', models.PositiveIntegerField()),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.tag')),
                ('todo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tododay', to='todo.todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
